### ISSUE TITLE
Should the triggers for ci-tests.yaml be less permissive?

### ISSUE THREAD

**Issue by bwpriest** [LLNL/ygm#87]

**Comment by steiltre** [comment]
I like this idea. With this change, would CI jobs still launch when additional changes are committed to an already-open PR?

**Comment by bwpriest** [comment]
Yes, the `pull_request` trigger launches jobs whenever a PR is created or updated

**Comment by rogerpearce** [comment]
What bout pushing into your fork, without at PR?   I've always found a that useful way to test during dev.

**Comment by steiltre** [comment]
Is there a way of specifying "all other branches"? If so, we could do something like
```
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: NOT [ main, develop ]
```
to get CI jobs running in forks as long as you work in a feature branch.

**Comment by bwpriest** [comment]
We could do something like
```
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ 'feature/**', 'hotfix/**']
```
This would trigger CI on pushes to branches whose names begin with 'feature/' or 'hotfix/'. We can use whatever prefixes we like. I am pretty sure that once you open a PR from such a branch to develop, subsequent pushes should only trigger a single batch of CI jobs.
